### ISSUE TITLE
Feature Request: Choose color for "Change Color when Notes are present"

### ISSUE THREAD

**Issue by patrickburk1988** [syl3r86/gm-notes#16]
For people who have certain types of color-blindness (and those who use modules that change the UI color, such as Ernie's Modern UI), the default green applied when "Change Color when Notes are present" is enabled can make the text unreadable. For example, here's how mine looks:
![](https://i.imgur.com/ScAhINr.png)

It's possible to override this with modules like Custom CSS Rules. For example, I can apply the following custom CSS —
```css
.open-gm-note[style*="green"] {
    background-color: rgba(var(--color-primary), 1) !important;
    color: rgba(var(--color-text-lightest), 1) !important;
}
```
— to make the text readable:
![](https://i.imgur.com/U2ps7Ax.png)

But not everyone is comfortable with manually altering the CSS. I know it's sort of a niche use case, but it would be cool to have an additional field in the settings to allow GMs to manually choose the text and/or background color to apply when notes are present.
